# Numpy practicing 

In [22]:
list1=[x*2 for x in range(2,27)]
print(list1)

[4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52]


In [23]:
!pip install names
import names 
list3=[names.get_full_name() for x in range(10)]
print(list3)

['Jason Cummings', 'Carol Anderson', 'Joseph Adams', 'Anna Meriwether', 'Samuel Vasquez', 'Keith Tesch', 'Jordan Smart', 'Ruby Hollis', 'Cristine Poling', 'Johnny Harris']


In [25]:
list4=[x for x in enumerate(list3,1)]  # enumerate requires iterable data type 
print(list4)

[(1, 'Jason Cummings'), (2, 'Carol Anderson'), (3, 'Joseph Adams'), (4, 'Anna Meriwether'), (5, 'Samuel Vasquez'), (6, 'Keith Tesch'), (7, 'Jordan Smart'), (8, 'Ruby Hollis'), (9, 'Cristine Poling'), (10, 'Johnny Harris')]


In [29]:
import numpy as np 
np_array_1=np.array(list4)
print(np_array_1)
print(type(np_array_1)) # nd array it means that this type of list is numpy array

[['1' 'Jason Cummings']
 ['2' 'Carol Anderson']
 ['3' 'Joseph Adams']
 ['4' 'Anna Meriwether']
 ['5' 'Samuel Vasquez']
 ['6' 'Keith Tesch']
 ['7' 'Jordan Smart']
 ['8' 'Ruby Hollis']
 ['9' 'Cristine Poling']
 ['10' 'Johnny Harris']]
<class 'numpy.ndarray'>


In [35]:
np_array=np.array([1,2,3,4])
np_array_test=np.array(["Smith","Charles",2,True]) 
# Numpy contain just one type of data it means that if our list consists of int,string and bool type of elements numpy will convert all of them to string
print(np_array)
print(type(np_array))
print(np_array_test)

[1 2 3 4]
<class 'numpy.ndarray'>
['Smith' 'Charles' '2' 'True']


In [45]:
np_array_2=np.arange(10) # create numpy array which the elements of array begin from 0 to 9. 
#The code block says that create a numpy array and it must be 10 elements 
print(np_array_2)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
np_array_3=np.arange(21)
print(np_array_3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [50]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"It is numpy array,\n {a} and type of it {type(a)}")
print(f"The elements which index is 2 {a[2]}")

It is numpy array,
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] and type of it <class 'numpy.ndarray'>
The elements which index is 2 [ 9 10 11 12]


In [52]:
# A vector is an array with a single dimension (there’s no difference between row and column vectors)
# A matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used.
# Dimensions are called axes

In [53]:
# Create numpy array which all elements of this array will be zero and it is called zeros nd array
print(np.zeros(5)) # output shown as float

[0. 0. 0. 0. 0.]


In [54]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [55]:
# We also have ones numpy array or ndarray and all elements of this array is one
print(np.ones(7)) # again output will be float

[1. 1. 1. 1. 1. 1. 1.]


In [56]:
print(np.ones(12))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [57]:
# Sometimes we create empty ndarray  instead of zeros ndarray due to the speed factor
# This array consists of randomly numbers
print(np.empty(8))

[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 6.56119178e-321 8.34445137e-308 2.14321575e-312]


In [59]:
print(np.arange(20))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [60]:
print(np.arange(100,130))

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129]


In [61]:
print(np.arange(125,180,5))

[125 130 135 140 145 150 155 160 165 170 175]


In [64]:
print(np.linspace(5,30,4)) # bu function verilen araliqda neçə interval olmasina gore bolur ededleri
# yani burada 5 ve 12 arasinda 4 beraber yere bolunmesini isteyir. Ilk ve son yani serhed olmasi ucun yazdigimiz araliqdaki ededler (5,30) eyni qalir

[ 5.         13.33333333 21.66666667 30.        ]


In [65]:
print(np.linspace(100,200,12))

[100.         109.09090909 118.18181818 127.27272727 136.36363636
 145.45454545 154.54545455 163.63636364 172.72727273 181.81818182
 190.90909091 200.        ]


In [70]:
print(np.ones(5,dtype=np.int64)) # normally it must return float64 type of data however when we want to convert the type of it we can use this code part
print(np.zeros(12,dtype=np.int64))

[1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0]


In [73]:
list_random=[19,24,3,10,15,30,43]
np_array_random=np.array(list_random)
print(np_array_random)
print(np.sort(np_array_random))

[19 24  3 10 15 30 43]
[ 3 10 15 19 24 30 43]


In [74]:
np_array_5=np.array([19,24,3,10,15,30,43])
print(np.sort(np_array_5))

[ 3 10 15 19 24 30 43]


In [80]:
b = np.array([[10,4],[3,1]]) # sort along the last axis, her setirdeki matricin ve ya vectorun icini sort edir 
np.sort(b)  

array([[ 4, 10],
       [ 1,  3]])

In [81]:
np.sort(b, axis=None)  # sort the flattened array

array([ 1,  3,  4, 10])

In [84]:
np.sort(b, axis=0)  # sort along the first axis

array([[ 3,  1],
       [10,  4]])

In [87]:
nd_array_1=np.array([x for x in range(0,15)])
nd_array_2=np.array([y for y in range(20,35)])
print(nd_array_1)
print(nd_array_2)
# to execute this operation we must pay attention the shape of numpy arrays if they aren't equal we will face error
print(nd_array_1+nd_array_2) 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34]
[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [92]:
nd_array_1=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])
nd_array_2=np.array([20,21,22,23,24,25,26,27,28,29,30,31,32,33,34])
print(nd_array_1)
print(nd_array_2)
print(np.concatenate((nd_array_1,nd_array_2))) # pay attention the number of bracelets

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34]


In [95]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
print(np.concatenate((x,y)))
print(np.shape(np.concatenate((x,y))))

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [97]:
np.concatenate((x, y), axis=0)
print(np.concatenate((x, y), axis=0))
print(np.shape(np.concatenate((x, y), axis=0)))

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [107]:
# ndarray.ndim will tell you the number of axes, or dimensions, of the array
# sondaki moterizelerin sayina gore bilmek olar
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
print(array_example)
print(f"Dimension of array is: {array_example.ndim}")

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]
Dimension of array is: 3


In [109]:
# ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape
array_example_1 = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
print(array_example_1)
print(f"Size of array is: {array_example_1.size}") # 6*4=24

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]
Size of array is: 24


In [111]:
# ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3)
array_example_2 = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
# print(array_example_2)
# shape of ndarray is also called as attribute of ndarray
print(f"Shape of array is: {array_example_2.shape}") # 3- dimension, 2-rows, 4-columns  row*column

Shape of array is: (3, 2, 4)


In [ ]:
# Note: The value before the comma specifies the row, the value after the comma specifies the column

In [ ]:
# np.mean(ndarray)
# np.std(ndarray)
# np.median(ndarray)
# np.corrcoef(ndarray)
# gk_heights=np_heights[np_positions=='GK']
# other_heights=np_heights[np_positions!='GK']